### PR TITLE
Map overlay fix

### PR DESCRIPTION
**Pull request by stephanlindauer**

### CODE REVIEW

**Comment by stephanlindauer** [comment]
please check code changes and how it works in the app before merging it. i am pretty confident but after i wont be there tomorrow someone else should also know what things have changed.
major improvement: no more redraws if they are not necessary plus no crash when the radius gets to big for bouding box.
@TIIUNDER @GammaG

**Comment by stephanlindauer** [comment]
i will build a new production binary and update the playstore

**Comment by TIIUNDER** [comment]
I check it

**Comment by stephanlindauer** [comment]
do u want to merge or should i? there seems to be merge conflicts...

**Comment by TIIUNDER** [comment]
merged it :-) I hope it is correct now, but looked good here. Please check if it's working for you

**Pull request merged**
